#!/bin/bash
VERSION=$(git tag | tail -1 | sed 's/.*\([0-9]\+\.[0-9]\+\.[0-9]\+\)/\1/')
MAJOR_VERSION=$(git tag | tail -1 | sed 's/.*\([0-9]\+\)\.[0-9]\+\.[0-9]\+/\1/')
if [ "$1" == "major" ]; then
	echo "$MAJOR_VERSION"
else
	echo "$VERSION"
fi
